server:
  port: 9895
spring:
  cloud:
    stream:
      function:
        # f1|f2表示连接两个函数进行处理
        definition:
      kafka:
        binder:
          brokers: 127.0.0.1:9093;127.0.0.1:9091;127.0.0.1:9092
          auto-create-topics: true
      bindings:
        source1-out-0:
          destination: test_topic11
          producer:
            partitionCount: 5
            partitionKeyExtractorName: myPartitionKeyExtractorStrategy
            partitionSelectorName: myPartitionSelectorStrategy
      poller:
        fixed-delay: 1000
      # 此时会自动解析为名为source1-out-x的bindings，可能有很多个binding，会匹配名称和streamBridge的bindingName一样的binding
      source: source1
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:9190/eureka
logging:
  level: debug
